### PR TITLE
Fix identity transactions request not using range specified in request.

### LINKED ISSUE #20: startTick and endTick params are ignored by the identity/transfers endpoint
**Describe the bug**
When calling the endpoint https://rpc.qubic.org/v2/identities/<IDENTITY_ADDRESS>/transfers with startTick and/or endTick params, they are not taking into consideration to filter the transfers result.

**To Reproduce**
Execute
https://rpc.qubic.org/v2/identities/LRNYYZCTSHPNDFTNVFANZCVPTUZCAQYTCIMRNNNUUEUMPLTCWBRZWIBATSKC/transfers?startTick=25200000&endTick=25574363&pageSize=250&desc=true

Items out of the defined range of ticks are returned.

**Expected behavior**
Only items which ticks >= to startTick and <= to endTick should be returned or empty array if they are not items matching.

**Logs**
-
**Environment**
-

**Additional context**
This was working a couple of weeks ago. This is being used by the web wallet to narrow down the transactions listed.

Image

### PR DESCRIPTION
**Pull request by LINCKODE**
Identity transfer transactions request now returns the transactions in the tick range specified by the request parameters.

Closes  #20

### CODE REVIEW

File: rpc/query.go [hunk 1]
```diff
@@ -126,13 +126,20 @@ func (s *StatusCache) fetchTickIntervals(ctx context.Context) ([]*statusPb.TickI
...
-	maxTick, err := qb.cache.GetMaxTick(ctx)
+func (qb *QueryBuilder) performIdentitiesTransactionsQuery(ctx context.Context, ID string, pageSize, pageNumber int, desc bool, reqStartTick, reqEndTick uint32) (result TransactionsSearchResponse, err error) {
+	statusMaxTick, err := qb.cache.GetMaxTick(ctx)
 	if err != nil {
 		return TransactionsSearchResponse{}, fmt.Errorf("getting max tick from cache: %w", err)
 	}
 
-	query, err := createIdentitiesQuery(ID, pageSize, pageNumber, desc, maxTick)
+	var maxTick uint32
+	if reqEndTick != 0 && reqEndTick <= statusMaxTick {
```
Comment (qubicmio) [inline rpc/query.go:136]: For me personally it's always easier to read the non-negated version. For example:
```
if endTick == 0 || endTick > statusMaxTick {
   maxTick = statusMaxTick
} else {
  maxTick = reqEndTick
}
```

Even better would be another name imo. maxTick is the one from the status. Then the tick we use to query would be `queryEndTick` for example. And in the request we would have `requestedStartTick` and `requestedEndTick`.

No need to change anything but I think that would have been easier to understand.
